apiVersion: v1
kind: Service
metadata:
  name: edu-orderer
  labels:
    run: edu-orderer
spec:
  type: NodePort
  selector:
    name: edu-orderer
  ports:
    - protocol: TCP
      nodePort: 30006
      targetPort: 30006
      port: 30006
      name: grpc