apiVersion: v1
kind: Service
metadata:
  name: edu-student-peer0
  labels:
    run: edu-student-peer0
spec:
  type: NodePort
  selector:
    name: edu-student-peer0
  ports:
    - protocol: TCP
      nodePort: 30000
      targetPort: 30000
      port: 30000
      name: grpc
    - protocol: TCP
      nodePort: 30002
      targetPort: 30002
      port: 30002
      name: events