apiVersion: v1
kind: Service
metadata:
  name: edu-academy-ca
  labels:
    run: edu-academy-ca
spec:
  type: NodePort
  selector:
    app: edu-academy-ca
  ports:
    - protocol: TCP
      nodePort: 30005
      targetPort: 7054
      port: 30005
      name: grpc
    # - protocol: TCP
    #  port: 7054
    #  name: grpc1