OrdererOrgs:
  - Name: Orderer
    Domain: certificate.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Academy
    Domain: academy.certificate.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Student
    Domain: student.certificate.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
