kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: certificate-orderer-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: certificate-orderer-files