kind: PersistentVolume
apiVersion: v1
metadata:
  name: certificate-student-peer0-pv
  labels:
    type: local
    name: certificate-student-peer0-files
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/certificate-student-peer0/var
    server: storage.local.parisi.biz
    readOnly: false