apiVersion: apps/v1
kind: Deployment
metadata:
  name: certificate-academy-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: certificate-academy-ca
  template:
    metadata:
      labels:
        app: certificate-academy-ca
    spec:
      volumes:
        - name: fabric-certificate-files
          persistentVolumeClaim:
            claimName: fabric-certificate-pvc
      containers:
        - name: certificate-academy-ca
          image: hyperledger/fabric-ca:1.4.4
          imagePullPolicy: IfNotPresent
          command:
            [
          		'sh',
          		'-c',
              'fabric-ca-server start -b admin:adminpw -d'
            ]
          env:
            - name: TZ
              value: 'America/Sao_Paulo'
            - name: FABRIC_CA_SERVER_CA_NAME
              value: 'certificate-academy-ca'
            - name: FABRIC_CA_SERVER_PORT
              value: '7054'
            - name: FABRIC_CA_SERVER_DEBUG
              value: 'true'
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: 'false'
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: /fabric/crypto-config/peerOrganizations/academy.certificate.com/ca/ca.academy.certificate.com-cert.pem
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: /fabric/crypto-config/peerOrganizations/academy.certificate.com/ca/df7db727f619cbe298bbb0735ce2db5bf52cba237d7e60a7ec4bf934d85857d3_sk
            - name: FABRIC_CA_SERVER_TLS_CERTFILE
              value: /fabric/crypto-config/peerOrganizations/academy.certificate.com/ca/ca.academy.certificate.com-cert.pem
            - name: FABRIC_CA_SERVER_TLS_KEYFILE
              value: /fabric/crypto-config/peerOrganizations/academy.certificate.com/ca/df7db727f619cbe298bbb0735ce2db5bf52cba237d7e60a7ec4bf934d85857d3_sk
            - name: GODEBUG
              value: 'netdns=go'
          volumeMounts:
            - mountPath: /fabric
              name: fabric-certificate-files
