apiVersion: v1
kind: Service
metadata:
  name: certificate-academy-ca
  labels:
    run: certificate-academy-ca
spec:
  type: NodePort
  selector:
    app: certificate-academy-ca
  ports:
    - protocol: TCP
      nodePort: 30004
      targetPort: 7054
      port: 30004
      name: grpc
    # - protocol: TCP
    #  port: 7054
    #  name: grpc1